name: master

on:
    push:
        branches:
            - master
        paths:
            - 'pom.xml'
            - 'settings.xml'
            - '.github/workflows/_master.yml'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v6

            -   name: JDK
                uses: actions/setup-java@v5
                with:
                    distribution: 'zulu'
                    java-version: 17

            -   name: Build
                env:
                    DEEPSEEK_API_KEY: ${{secrets.DEEPSEEK_API_KEY_TEST}}
                    KIMI_API_KEY: ${{secrets.KIMI_API_KEY_TEST}}
                    TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN_TEST}}
                    TELEGRAM_CHATBOT: ${{secrets.TELEGRAM_CHATBOT_TEST}}
                run: |
                    mvn -s settings.xml validate
                    mvn package

            -   name: Upload app bundle
                uses: actions/upload-artifact@v6
                with:
                    name: appbundle
                    path: modules/kokibot/target/*.jar

            -   name: Upload JaCoCo Report
                uses: actions/upload-artifact@v6
                with:
                    name: jacoco-report
                    path: modules/kokibot/target/site/jacoco/**/*

            -   name: Generate JaCoCo Badge
                uses: cicirello/jacoco-badge-generator@v2
                with:
                    generate-branches-badge: false
                    jacoco-csv-file: modules/kokibot/target/site/jacoco/jacoco.csv
                    coverage-badge-filename: kokibot-jacoco.svg

            -   name: Commit the badge (if it changed)
                continue-on-error: true
                run: |
                    if [[ `git status --porcelain` ]]; then
                      git config user.email "actions@github.com"
                      git config user.name "GitHub Actions"
                      git add -A
                      git commit -m "Autogenerated JaCoCo coverage badge"
                      git push
                    fi
