name: master

on:
    push:
        branches:
            - pr
        paths:
            - 'pom.xml'
            - 'settings.xml'
            - '.github/workflows/_pr.yml'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v6

            -   name: JDK
                uses: actions/setup-java@v5
                with:
                    distribution: 'zulu'
                    java-version: 17

            -   name: Build
                env:
                    DEEPSEEK_API_KEY: ${{secrets.DEEPSEEK_API_KEY_TEST}}
                    KIMI_API_KEY: ${{secrets.KIMI_API_KEY_TEST}}
                    TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN_TEST}}
                    TELEGRAM_CHATBOT: ${{secrets.TELEGRAM_CHATBOT_TEST}}
                run: |
                    mvn -s settings.xml validate
                    mvn package
