name: pr

on:
    pull_request:
        paths-ignore:
            - '**.md'
            - 'docs/**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v7

            -   name: JDK
                uses: actions/setup-java@v5
                with:
                    distribution: 'zulu'
                    java-version: 17

            -   name: Set up Python
                uses: actions/setup-python@v6
                with:
                    python-version: '3.14' # MarkItDown requires Python 3.9+

            -   name: Install MarkItDown
                run: |
                    python -m pip install --upgrade pip
                    pip install 'markitdown[all]'

            -   name: Build
                env:
                    KOKIBOT_DEEPSEEK_API_KEY: ${{secrets.DEEPSEEK_API_KEY}}
                    KOKIBOT_GEMINI_API_KEY: ${{secrets.GEMINI_API_KEY}}
                    KOKIBOT_KIMI_API_KEY: ${{secrets.KIMI_API_KEY}}
                    KOKIBOT_TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
                run: |
                    mvn validate
                    mvn package
